### ISSUE TITLE
Source maps with karma's coffee-loader

### ISSUE THREAD

**Issue by ggoodale** [webpack-contrib/karma-webpack#13]
I'm trying to use karma(/mocha/chai/phantomjs+chrome) and webpack's coffee-loader together, and my stack traces on test failures don't appear to be taking advantage of source maps.  I can see coffee-loader returning the generated source map info, and there's a sourceMapUrl appended to the output file, but my test output looks like:

```
FAILED TESTS:
  Media
    when rendered with no image
      ✗ should be an img
        PhantomJS 1.9.7 (Mac OS X)
      AssertionError: expected 1 to equal 0
          at /Users/ggoodale/Projects/snip/client-root/test/spec/react_components/Media_spec.coffee:11122
          at assertEqual (/Users/ggoodale/Projects/snip/client-root/test/spec/react_components/Media_spec.coffee:18517)
          at /Users/ggoodale/Projects/snip/client-root/test/spec/react_components/Media_spec.coffee:29137
          at /Users/ggoodale/Projects/snip/client-root/test/spec/react_components/Media_spec.coffee:83
          at callFn (/Users/ggoodale/Projects/snip/client-root/node_modules/mocha/mocha.js:4338)
          at /Users/ggoodale/Projects/snip/client-root/node_modules/mocha/mocha.js:4331
          at /Users/ggoodale/Projects/snip/client-root/node_modules/mocha/mocha.js:4728
          at /Users/ggoodale/Projects/snip/client-root/node_modules/mocha/mocha.js:4819
          at next (/Users/ggoodale/Projects/snip/client-root/node_modules/mocha/mocha.js:4653)
          at /Users/ggoodale/Projects/snip/client-root/node_modules/mocha/mocha.js:4663
```

(note that the error claims to have occurred on line 11222 of Media.coffee, which is 43 lines long.)

The relevant part of my karma.conf.js:

``` javascript
    webpack: {
      cache: true,
      debug: true,
      devtool: '@inline-source-map',
      module: {
        preLoaders: [],
        loaders: [{
          test: /\.coffee$/,
          exclude: 'node_modules',
          loader: 'coffee-loader'
        }, {
          test: /\.css$/,
          loader: 'style!css'
        }, {
          test: /\.gif/,
          loader: 'url-loader?limit=10000&mimetype=image/gif'
        }, {
          test: /\.jpg/,
          loader: 'url-loader?limit=10000&mimetype=image/jpg'
        }, {
          test: /\.png/,
          loader: 'url-loader?limit=10000&mimetype=image/png'
        }]
      },
      resolve: {
        extensions: ["", ".web.coffee", ".web.js", ".js.coffee", ".coffee", ".js"],
        modulesDirectories: ["web_modules", "node_modules", "src/js/react_components", "test/spec"]
      }
    },
```

**Comment by jeffling** [comment]
I'm also running into this, wondering if you found a fix or workaround @ggoodale @sokra ?

**Comment by dana11235** [comment]
I'm still seeing this. Has anyone figured out a workaround?

**Comment by sokra** [comment]
Maybe one of this plugins help:

https://www.npmjs.com/package/karma-sourcemap-loader
https://www.npmjs.com/package/karma-source-map-support

**Comment by dana11235** [comment]
I've tried a few different sourcemap loaders with no success.

The problem doesn't appear to be the sourcemap loader - in fact you can see that it is loading *some* sourcemap (the line numbers reference a coffeescript file). It's just that it appears to be generating a sourcemap for the single file gotten by concatenating all of the dependencies, rather than using the input coffeescript files to generate the sourcemap.

I had sourcemap support working just fine when I was using requirejs (using a similar karma config), so I'm guessing that the issue has something to do with the way that karma-webpack is processing the files/generating sourcemaps.

**Comment by llwt** [comment]
It's been a couple months since this was brought up, I'm running into the same issue. Has anyone found a workable solution yet? 

I tried the karma sourcemap plugins before finding this thread with no success.

**Comment by snario** [comment]
+1

**Comment by KeriWarr** [comment]
+2

**Comment by Morantron** [comment]
+3

**Comment by vectart** [comment]
+100500

**Comment by danawoodman** [comment]
Anyone able to get this to work?

**Comment by jjoos** [comment]
@dana11235 I don't think it's generating any source maps. Currently debugging this to figure out what is wrong, my current guess is some compatibility issue between `webpack` and `karma-webpack`.

**Comment by vectart** [comment]
I've got that working in Chrome by combination of https://www.npmjs.com/package/karma-source-map-support and inline sourcemaps:
```js
config.set({
    frameworks: ['source-map-support', /*...*/],

    webpack: {
        devtool: '#cheap-module-inline-source-map',
        /*...*/
    },

    /*...*/
});
```

**Comment by jjoos** [comment]
We had a few problems with our setup:
- when only using the coffee-jsx-loader, something went wrong with generating the source maps they were never returned to karma. Including `babel-loader` and having a javascript entry file that was loaded by babel made it magically work. Haven't yet found the root cause for this (Maybe babel fixes some issue with the source maps generated by the `coffee-jsx-loader`?)
- mocha only returned line numbers on error (no column information), which triggered a bug in karma (pull request here https://github.com/karma-runner/karma/pull/1549 , you can use this source for npm: 'git+https://github.com/jjoos/karma.git#with-static-assets'  )

So got it working with the `karma-sourcemap-loader`, but there still there is work to be done.

**Comment by brianmhunt** [comment]
FWIW, I get sensible source map output by using `devtool: 'inline-source-map'`

**Comment by fixpunkt** [comment]
+1 Still can't make this work, even with babel-loader. Where would I begin debugging this?

**Comment by SPSpwetter** [comment]
I got this working. Normal usage (webpack each test separately), using the source-map-loader

`devtool: eval
`
normal usage:

```
		files: [
			'src/test/*Test.coffee'
                       ]

```      
source map loader:

```
		preprocessors: {
			# only specify one entry point
			# and require all tests in there
			'**/*.coffee': ['webpack','sourcemap']
		plugins: [
		  'karma-sourcemap-loader',

```

**Comment by anbiniyar** [comment]
After manually putting in log statements, it seems like `coffee-loader` does generate the sourcemap as requested by webpack. However when `karma-webpack webpackPlugin.readFile` is called, the file returned doesn't have a sourcemap. That's as far as I got and I am stuck.

**Comment by sshev** [comment]
Looks like out of the box webpack does not generate source maps for files other than `.js` and `.css` extensions ([proof](https://github.com/webpack/webpack/blob/5b5775f9e2fc73fea46629f2d6a3ed7a1f8424d3/lib/SourceMapDevToolPlugin.js#L35))
Check my solution here https://github.com/webpack/karma-webpack/issues/109#issuecomment-224961264 - maybe it will help.

**Comment by d3viant0ne** [comment]
Need to know if this is still an issue after @sshev's resolution which for reference is a variation of what I use to get 1.x working with TypeScript. For the sake of efficiency, we are starting with current versions and the team can work back from there. 

If this is still an issue on a recent version of the loader & it's peerDeps, please respond here so we can get this properly triaged.

**Comment by abirmingham** [comment]
I'm using webpack 1.13.3, karma 1.3.0, karma-webpack 1.8.0, karma-sourcemap-loader 0.3.7, typescript 1.8.10. @sshev's solution works great for phantomjs but console errors in chrome still refer to _https://localhost:9876_ rather than _webpack:///_. This means that clicking on exceptions in the browser console leads to the giant webpack file, rather than the original source files.

The good news is that the payload is mapped, and the original source files **are** included in Chrome under _webpack:///_. Further, setting breakpoints in those files does succeed. So I can set breakpoints in the giant webpack file (e.g. _https://localhost:9876/test/MyComponentTest.ts_), the original source file (e.g. _webpack:///./test/MyComponentTest.ts_), and in files imported by the original source file (e.g. _webpack:///./src/MyComponent.ts_). Breakpoints to all three of those locations work as expected.

However, I'd hope that console stack traces could refer to the webpack:/// file, not the https:// file.
