### ISSUE TITLE
Error: no such file or directory /_karma_webpack_/.

### ISSUE THREAD

**Issue by yangit** [webpack-contrib/karma-webpack#230]
**I'm submitting a bug report**

**Webpack version:**
2.2.1

**Webpack Karma version**:
2.0.2

**Karma version**:
1.5.0

**Please tell us about your environment:**
OSX 10.12.3

**Current behavior:**
Any plugin trying to write to assets folder will fail because karma webpack [rewrites](https://github.com/webpack-contrib/karma-webpack/blob/v2/src/karma-webpack.js#L49)  `webpackOptions.output` like so.

```
webpackOptions.output.path = '/_karma_webpack_/' + indexPath;
webpackOptions.output.publicPath = '/_karma_webpack_/' + publicPath;
```
Since that path `/_karma_webpack_/...` has never existed the plugin which tries to write to asset folder will fail with `ENOENT can't open file` error.

**Expected/desired behavior:**
Do not change `webpackOptions.output.path` so that plugins can write files to asset folder w\o any problem.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

I had 2 plugins failing:
`webpack-bundle-analyzer` and `sw-precache-webpack-plugin`.
The first one is much easier to configure but it does not really mater. What matters is that plugins rightfully expect to get valid path in `webpackOptions.output.path` and they are getting some junk.

```
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
webpackConfig.plugins.push(new BundleAnalyzerPlugin({
    openAnalyzer: false,
    generateStatsFile: true,
    statsFilename: 'webpack.stats.json',
    analyzerMode: 'static',
    reportFilename: 'webpack.bundleinfo.html'
  }))
```

With this config `BundleAnalyzerPlugin` will try to output 2 files in `webpackOptions.output.path` and will fail.

**Comment by davetron5000** [comment]
I'm also having this issue, and I can't understand how the code as written is intended to work.  It appears to want to have webpack always write to `/_karma_webpack` in the **root** directory of the machine, which is likely never writable.  `output.path` is [treated as an absolute path](https://webpack.js.org/configuration/output/#output-path)

I don't see how this could've ever worked, so I'm assuming I just don't understand what this code is trying to do, so then I can figure out how to fix it or work around it.

**Comment by Luxiyalu** [comment]
@davetron5000 We're running into the same problem. In `karma-webpack`'s source, they said:

```Javascript
// Must have the common _karma_webpack_ prefix on path here to avoid
// https://github.com/webpack/webpack/issues/645
webpackOptions.output.path = '/_karma_webpack_/' + indexPath;
webpackOptions.output.publicPath = '/_karma_webpack_/' + publicPath;
```

https://github.com/webpack/webpack/issues/645 was an issue back in 2014 about infinite loop due to two compilers both having `outputPath` set to `"/"`.

First of all, I don't see why any project should have their `outputPath` set to `"/"`. Second, the solution should be to warn people against using `"/"` as `outputPath`, not force rewriting `karma-webpack`'s own `outputPath` to another folder directly under root.

All npm wants is an absolute path. Please allow customization at least.

**Comment by dentuzhik** [comment]
I have the same problem with a slightly different error message:
```
Error: EACCES: permission denied, mkdir '/_karma_webpack_'
```
While this is definitely legit bug, as aa workaround I just stripped the `BundleAnalyzer` from the config which is used by `karma-webpack`

**Comment by Ian5015** [comment]
ENOENT can't open file error as well, has anyone had success finding a workaround?

**Comment by jvmccarthy** [comment]
Started running into this as well, and I think I figured out what is happening. To host files for karma, karma-webpack uses [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware), which uses an in-memory file system. The `/_karma_webpack/` directory only exists in the in-memory file system. However, certain plugins interpret these paths as directories on the host OS file system (the actual disk) instead of in-memory. For @dentuzhik, this was the `BundleAnalyzer`. For me, it was the [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin).

**Be very careful with the webpack plugins you use with karma-webpack and remove as many plugins as you can in the webpack config used with karma-webpack.** A number of plugins do not understand these in-memory file system paths.

**Comment by 8bitDesigner** [comment]
I've got a fix on my branch for this guy to point all the `/_karma_webpack_/` things to `/tmp/_karma_webpack_/` instead: https://github.com/Fullscreen/karma-webpack/commit/4699a43357fc5e812fc665ce84371aef2fb646ae

**Comment by liangzeng** [comment]
### Webpack version:
3.11.0

### Webpack Karma version:
2.0.9

### Karma version:
2.0.0

### environment:
OSX 10.13.3

![image](https://user-images.githubusercontent.com/8503065/36637711-129382fc-1a1d-11e8-88e0-4a8f8fa1829b.png)

```
cd /var/folders/xv/n34wwh4j1klf_vq2w80rvv400000gn/T/_karma_webpack_/  
```

> No such file or directory
