### ISSUE TITLE
Indicate if Webpack V2 is supported in the Readme

### ISSUE THREAD

**Issue by Vaccano** [webpack-contrib/karma-webpack#240]
**I'm submitting a feature request**

**Webpack version:**
2.3.2

**Webpack Karma version**:
2.0.3

**Karma version**:
1.5.0

**Please tell us about your environment:**
 Windows 7

**Current behavior:**
Read Me does not indicate if the documentation is for Webpack 2 or for Webpack 1

**Expected/desired behavior:**
The Read Me would clearly indicate if the examples are for Webpack 2 or Webpack 1 (or both)

* **What is the motivation / use case for changing the behavior?**
So that users of the project can know if errors they are having are due to incompatibility with Webpack 2.

**Comment by perymimon** [comment]
super important , co's that is `karma-webpack`

**Comment by brianmhunt** [comment]
Note that if you installs `karma-webpack`, then later add `webpack` 2.x to `package.json`, you need to delete the `webpack` installed for `karma-webpack` (i.e. there's no peer webpack version so karma-webpack will install and use its own webpack at `node_modules/karma-webpack/node_modules/webpack`), because it'll be version 1.x.

**Comment by BuonOmo** [comment]
So, if update to webpack 2, what is the minimum required version of `karma-webpack`?

**Comment by grofit** [comment]
Just to mention webpack 3 is out now too, so would be good to mention that too.
