### ISSUE TITLE
Watch mode is far too sensitive

### ISSUE THREAD

**Issue by noahgrant** [webpack-contrib/karma-webpack#253]
**I'm submitting a bug report** (though it could be a support issue if this is just a configuration bug)

Please excuse me if this ticket is misplaced and if this should actually be placed with karma itself—since my issue is with watching any file (not just the entry file that Karma watches), I'm thinking that the issue is here (or possibly with webpack itself).

My issue is that using karma (v1.7) and karma-webpack (v2.0.4), tests are re-run, triggered by the watcher, _simply by opening a file in the tree_. I find it pretty disruptive to my testing workflow.

**Webpack version:**
2.x

**Webpack Karma version**:
2.0.4

**Karma version**:
1.7

**Please tell us about your environment:**
OSX 10.x

**Browser:** [Chrome 59]

**Current behavior:**
Page reload is triggered every time a file is opened

**Expected/desired behavior:**
Page reload is triggered every time a file is saved

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

```js
module.exports = (config) => {
  config.set({
    basePath: '../../',
    browsers: ['Chrome'],
    client: {
      captureConsole: false,
      clearContext: false,
      useIframe: false
    },
    frameworks: ['jasmine'],
    singleRun: env.testCI(),
    files: [
      {pattern: 'path/to/entryfile.js', watched: false}
    ],
    plugins: [
      'karma-chrome-launcher',
      'karma-jasmine',
      'karma-jasmine-html-reporter',
      'karma-webpack'
    ],
    preprocessors: {
      'path/to/helperfile.js': ['webpack'],
      'path/to/entryfile.js': ['webpack']
    },
    port: 5324,
    webpack: _.omit(getWebpackConfig(), 'entry'),
    webpackServer: {noInfo: true},
    reporters: ['progress', 'kjhtml']
  });
};
```

Again, I really apologize is this is misplaced, and if so, please close and I'll file on SO.

**Comment by rhys-e** [comment]
I've had a similar issue. Basically whenever a file is changed next time `karma-webpack` is run it'll re-compile multiple times mid-test.

The offending line is `webpackOptions.watch = true;` in `karma-webpack.js`. If I comment this out everything works fine (I don't actually care about watching in this way, so it works for my purposes).

Unfortunately I've yet to find a way to turn this flag off without modifying `karma-webpack` since it currently clones the `webpack` config, so I can't access it or put a setter/getter on it.

**Comment by yscik** [comment]
The problem is, with something `require.context('.', true, /\.test.js$/)`, webpack will be watching the entire directory, including the contents of `.git`, `node_modules/.cache`, and whatever local file or folder the IDE creates (and probably updates when opening a file). 

The webpackMiddleware can be configured to ignore these:
```
  webpackMiddleware: {
      watchOptions: {
        ignored: [/\/\./, 'node_modules']
      }
    }
```

**Comment by Blackbaud-SteveBrush** [comment]
@yscik solution works. Related Webpack documentation:
"If you use require.context, webpack will watch your entire directory. You will need to ignore files and/or directories so that unwanted changes will not trigger a rebuild."
https://webpack.js.org/configuration/watch/
